from __future__ import annotations

import json
import os
import re
import sqlite3
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, Mapping, Sequence
from urllib.parse import quote_plus

import numpy as np

try:
    import pandas as pd
except Exception as exc:  # pragma: no cover
    raise ImportError("pandas is required for project scaffold table readers") from exc

from config import (
    BiasSpec,
    CapabilitySpec,
    ExecutionSpec,
    FlowAssemblySpec,
    NumericizerSpec,
    TrainerAssemblySpec,
    coerce_execution_spec,
    describe_execution_spec_schema,
    describe_trainers,
)
from core.common.contracts import ProcessedDataset
from core.orchestration.workflow import (
    ModelSpec,
    SemanticTrainFlowSpec,
    TrainDataBundle,
    TrainPortfolioResult,
    TrainFlowResult,
    run_semantic_portfolio_flow,
    run_semantic_train_flow,
)


_PROJECT_FOLDERS = [
    "catalog",
    "schema",
    "numericizer",
    "pipeline",
    "bias",
    "trainer",
    "workflow",
    "data",
    "configs",
    "runs",
    "docs",
    "scripts",
]

_NON_PACKAGE_FOLDERS = {"data", "configs", "runs", "docs"}

_FOLDER_DESCRIPTIONS: Dict[str, str] = {
    "catalog": "Project-local registration and discoverability index.",
    "schema": "Task/domain schema definitions for raw cells and semantic columns.",
    "numericizer": "Semantic-to-numeric conversion rules and codecs.",
    "pipeline": "Feature processing pipeline components.",
    "bias": "Training preference and regularization-style policies.",
    "trainer": "Custom trainer wrappers or trainer presets for this project.",
    "workflow": "Task orchestration around train/eval/export stages.",
    "data": "Input tables and intermediate cleaned data.",
    "configs": "Scaffold run configs (data + train).",
    "runs": "Artifacts and reports generated by scaffold runs.",
    "docs": "Project notes, assumptions, and experiment logs.",
    "scripts": "One-off helper scripts for this project.",
}

_ENV_BRACED_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


def _expand_env_refs(value: str) -> str:
    """Expand `%VAR%`, `$VAR`, and `${VAR}` references in string values."""
    text = os.path.expandvars(str(value))

    def _replace(match: re.Match[str]) -> str:
        key = str(match.group(1))
        raw = os.environ.get(key)
        if raw is None:
            return match.group(0)
        return str(raw)

    return _ENV_BRACED_PATTERN.sub(_replace, text)


def _as_name_tuple(value: Any) -> tuple[str, ...]:
    if value is None:
        return tuple()
    if isinstance(value, str):
        text = str(value).strip()
        return tuple() if not text else (text,)
    out: list[str] = []
    for item in value:
        key = str(item).strip()
        if key:
            out.append(key)
    return tuple(out)


def _normalize_source_kind(value: Any) -> str:
    return str(value or "csv").strip().lower()


@dataclass(frozen=True)
class TableDataSpec:
    csv_path: str = ""
    sources: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    merge_on: Sequence[str] = field(default_factory=tuple)
    merge_how: str = "inner"
    base_source: str | None = None
    target_col: str = ""
    date_col: str | None = "date"
    drop_cols: Sequence[str] = field(default_factory=tuple)
    feature_recipe: str = "raw_all_numeric"  # raw_all_numeric | work_ci_interval_v1
    split_mode: str = "fold_flag"  # fold_flag | ratio
    test_fold_col: str = "test_fold_10"
    test_ratio: float = 0.2
    random_seed: int = 42


@dataclass(frozen=True)
class TrainStageSpec:
    trainer_key: str = "xgboost"
    pipeline_key: str = "identity"
    trainer_params: Mapping[str, Any] = field(default_factory=dict)
    pipeline_params: Mapping[str, Any] = field(default_factory=dict)
    biases: Sequence[Mapping[str, Any]] = field(default_factory=tuple)

    numericizer_key: str = "default"
    numericizer_params: Mapping[str, Any] = field(default_factory=dict)
    model_spec: Mapping[str, Any] | None = None
    model_specs: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    training_init: Mapping[str, Any] | None = None
    state_backend: Mapping[str, Any] | None = None
    execution: Mapping[str, Any] | None = None
    capabilities: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    capability_strict: bool = False

    eval_splits: Sequence[str] = ("train", "test")
    output_dir: str = "runs/scaffold_run"
    run_name: str = "scaffold_run"
    portfolio_parallel_mode: str = "serial"  # serial | thread | process
    portfolio_max_workers: int | None = None
    portfolio_fail_fast: bool = True
    portfolio_gpu_strategy: str = "none"  # none | fixed | round_robin | auto
    portfolio_gpu_devices: Sequence[str | int] = field(default_factory=tuple)


@dataclass(frozen=True)
class ScaffoldSpec:
    data: TableDataSpec
    train: TrainStageSpec


def _write_file(path: Path, content: str, *, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    path.write_text(content, encoding="utf-8")


def _folder_readme(name: str) -> str:
    desc = _FOLDER_DESCRIPTIONS.get(name, "Module directory.")
    return dedent(
        f"""\
        # {name}

        - Responsibility: {desc}
        - Boundary: keep only this layer's concern.
        - Rule: no hidden cross-layer coupling.
        """
    )


def _root_readme(project_name: str) -> str:
    return dedent(
        f"""\
        # {project_name}

        mlblack standard scaffold project.

        ## Quickstart
        1. Fill `configs/train_config.json`
           or start from `configs/train_config_stagewise_grouped.json`
        2. Review `config.py` presets and defaults
        3. Run `python run_train.py --config configs/train_config.json`
        4. Inspect `runs/` for artifact and flow report

        ## Three-File Entry (nsgablack-style)
        - `config.py`: registration and policy defaults
        - `assembly.py`: compose spec and run flow
        - `run_train.py`: execution CLI only

        ## Structure
        - `schema/`, `numericizer/`, `pipeline/`, `bias/`
        - `trainer/`, `workflow/`, `catalog/`
        - `data/`, `configs/`, `runs/`, `docs/`

        ## Catalog
        - `catalog/entries.toml` ships with a project-local sample entry so the project catalog view works immediately.

        ## Notes
        - Upstream data cleaning stays outside mlblack.
        - This scaffold starts from processed table data and trains a surrogate.
        - `schema/execution_schema.py` exposes the formal L0 execution choices for UI/config tooling.
        - `schema/trainer_contracts.py` snapshots trainer contracts and execution resource profiles for UI/config tooling.
        - `symbolic_stagewise` supports both flat and grouped `train.trainer_params`.
        - Flat syntax remains compatible; grouped syntax is recommended for readability.
        - If flat and grouped keys target the same field, flat wins.
        """
    )


def _start_here() -> str:
    return dedent(
        """\
        # START_HERE

        ## 1) Prepare data
        - Put your processed csv into `data/`.
        - Make sure target column is ready.

        ## 2) Register defaults (`config.py`)
        - Pick or edit `TRAINER_PRESETS`.
        - Choose `train.preset_key` in json.
        - Read `schema/execution_schema.py` if you need the formal L0 execution enum/field catalog.
        - Read `schema/trainer_contracts.py` if you need trainer capability / execution resource snapshots for UI or config validation.

        ## 3) Assemble + Run
        ```powershell
        python run_train.py --config configs/train_config.json
        ```

        Stagewise grouped example config:
        ```powershell
        python run_train.py --config configs/train_config_stagewise_grouped.json
        ```

        ## 4) Inspect outputs
        - Artifact: `runs/<run_name>/artifact/`
        - Report: `runs/<run_name>/flow_report.json`
        - Project Catalog: `catalog/entries.toml`

        ## 5) `symbolic_stagewise` grouped config example
        `train.trainer_params` supports both flat and grouped styles.
        For new configs, prefer grouped style:

        ```json
        {
          "train": {
            "preset_key": "baseline_stagewise",
            "trainer_params": {
              "strategy": {
                "force_linear_base": "auto",
                "keep_search_trace": true
              },
              "search_core": {
                "max_added_terms": 12,
                "topk_features": 8
              },
              "search_inner_opt": {
                "enabled": true,
                "method": "adam"
              }
            }
          }
        }
        ```

        Rule:
        - flat + grouped can coexist in the same `trainer_params`
        - if both write the same field, flat wins
        """
    )


def _project_catalog_entries_template() -> str:
    return dedent(
        """\
        [[entry]]
        key = "preset:local_demo"
        kind = "preset"
        name = "local_demo"
        summary = "Project-local demo preset entry for project catalog view."
        tags = ["project", "demo", "local"]

        [entry.fields]
        family = "neural"
        head = "point"
        runtime_backend = "torch"
        status = "project_local"
        title_zh = "项目本地预设"
        summary_zh = "用于演示 project 视图的本地 preset 条目。"
        use_when_zh = ["需要验证 project catalog 接线是否正常时。"]

        [entry.relations]
        family = ["family:neural"]
        head = ["head:point"]
        component = []
        provider = []
        plugin = []
        """
    )


def _sample_train_config() -> str:
    payload = {
        "data": {
            "csv_path": "data/processed.csv",
            "target_col": "target",
            "date_col": "date",
            "drop_cols": [],
            "feature_recipe": "raw_all_numeric",
            "split_mode": "ratio",
            "test_fold_col": "test_fold_10",
            "test_ratio": 0.2,
            "random_seed": 42,
        },
        "train": {
            "preset_key": "baseline_xgboost",
            "trainer_params": {
                "artifact_id": "surrogate_v1",
                "n_estimators": 420,
                "max_depth": 6,
                "learning_rate": 0.05,
            },
            "pipeline_params": {},
            "biases": [],
            "numericizer_params": {},
            "model_spec": {
                "model_id": "scaffold_default_model",
            },
            "training_init": {
                "mode": "fresh"
            },
            "state_backend": {
                "context": {
                    "backend": "memory"
                },
                "snapshot": {
                    "backend": "memory"
                }
            },
            "capabilities": [
                {
                    "key": "noop",
                    "params": {
                        "name": "scaffold_trace",
                        "priority": 0,
                    },
                }
            ],
            "execution": {
                "backend": "serial",
                "max_workers": None,
                "fail_fast": True,
                "gpu_strategy": "none",
                "gpu_devices": [],
                "default_device": None
            },
            "capability_strict": False,
            "eval_splits": ["train", "test"],
            "output_dir": "runs/scaffold_run",
            "run_name": "scaffold_run",
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def _sample_train_config_stagewise_grouped() -> str:
    payload = {
        "data": {
            "csv_path": "data/processed.csv",
            "target_col": "target",
            "date_col": "date",
            "drop_cols": [],
            "feature_recipe": "raw_all_numeric",
            "split_mode": "ratio",
            "test_fold_col": "test_fold_10",
            "test_ratio": 0.2,
            "random_seed": 42,
        },
        "train": {
            "preset_key": "baseline_stagewise",
            "trainer_params": {
                "artifact_id": "surrogate_stagewise_demo",
                "strategy": {
                    "force_linear_base": "auto",
                    "keep_search_trace": True,
                },
                "search_core": {
                    "max_added_terms": 12,
                    "topk_features": 8,
                    "max_expr_depth": 6,
                },
                "search_family": {
                    "unary_ops": ["square", "sin", "cos", "tanh"],
                    "auto_nested_allowed_ops": ["square", "sin", "cos", "tanh"],
                },
                "search_online_beam": {
                    "enabled": True,
                    "width": 6,
                    "bundle_size": 3,
                },
                "search_inner_opt": {
                    "enabled": True,
                    "method": "adam",
                    "adam_steps": 60,
                },
            },
            "pipeline_params": {},
            "biases": [],
            "numericizer_params": {},
            "model_spec": {
                "model_id": "scaffold_stagewise_model",
            },
            "training_init": {
                "mode": "fresh"
            },
            "state_backend": {
                "context": {
                    "backend": "memory"
                },
                "snapshot": {
                    "backend": "memory"
                }
            },
            "capabilities": [
                {
                    "key": "noop",
                    "params": {
                        "name": "scaffold_trace",
                        "priority": 0,
                    },
                }
            ],
            "execution": {
                "backend": "serial",
                "max_workers": None,
                "fail_fast": True,
                "gpu_strategy": "none",
                "gpu_devices": [],
                "default_device": None
            },
            "capability_strict": False,
            "eval_splits": ["train", "test"],
            "output_dir": "runs/scaffold_stagewise_run",
            "run_name": "scaffold_stagewise_run",
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def _execution_schema_template() -> str:
    payload = json.dumps(describe_execution_spec_schema(), ensure_ascii=False, indent=2)
    return dedent(
        f"""\
        from __future__ import annotations

        import json
        from typing import Any, Dict


        EXECUTION_SPEC_SCHEMA: Dict[str, Any] = json.loads(
            r'''{payload}'''
        )


        def get_execution_spec_schema() -> Dict[str, Any]:
            return json.loads(json.dumps(EXECUTION_SPEC_SCHEMA))
        """
    )


def _trainer_contracts_schema_template() -> str:
    contracts_payload = json.dumps(describe_trainers(), ensure_ascii=False, indent=2)
    resource_profiles = {
        str(key): dict(dict(value).get("contract", {}).get("execution_resources", {}))
        for key, value in dict(describe_trainers()).items()
    }
    resources_payload = json.dumps(resource_profiles, ensure_ascii=False, indent=2)
    return dedent(
        f"""\
        from __future__ import annotations

        import json
        from typing import Any, Dict


        TRAINER_CONTRACTS: Dict[str, Dict[str, Any]] = json.loads(
            r'''{contracts_payload}'''
        )

        TRAINER_RESOURCE_PROFILES: Dict[str, Dict[str, Any]] = json.loads(
            r'''{resources_payload}'''
        )


        def get_trainer_contracts() -> Dict[str, Dict[str, Any]]:
            return json.loads(json.dumps(TRAINER_CONTRACTS))


        def get_trainer_resource_profiles() -> Dict[str, Dict[str, Any]]:
            return json.loads(json.dumps(TRAINER_RESOURCE_PROFILES))
        """
    )


def _config_template() -> str:
    return dedent(
        """\
        from __future__ import annotations

        from dataclasses import dataclass, field
        from typing import Any, Dict, Mapping, Sequence

        from schema.execution_schema import EXECUTION_SPEC_SCHEMA
        from schema.trainer_contracts import TRAINER_CONTRACTS, TRAINER_RESOURCE_PROFILES


        PROJECT_NAME = "mlblack_scaffold_project"
        EXECUTION_BACKEND_CHOICES = tuple(str(x) for x in EXECUTION_SPEC_SCHEMA["fields"]["backend"]["enum"])
        EXECUTION_GPU_STRATEGY_CHOICES = tuple(str(x) for x in EXECUTION_SPEC_SCHEMA["fields"]["gpu_strategy"]["enum"])
        EXECUTION_DEFAULTS = dict(EXECUTION_SPEC_SCHEMA.get("defaults", {}))
        TRAINER_CONTRACT_KEYS = tuple(sorted(str(x) for x in TRAINER_CONTRACTS.keys()))


        @dataclass(frozen=True)
        class TrainerPreset:
            trainer_key: str
            pipeline_key: str = "identity"
            trainer_params: Mapping[str, Any] = field(default_factory=dict)
            pipeline_params: Mapping[str, Any] = field(default_factory=dict)
            biases: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
            numericizer_key: str = "default"
            numericizer_params: Mapping[str, Any] = field(default_factory=dict)
            model_spec: Mapping[str, Any] | None = None
            training_init: Mapping[str, Any] | None = None
            state_backend: Mapping[str, Any] | None = None
            execution: Mapping[str, Any] | None = None
            capabilities: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
            capability_strict: bool = False


        TRAINER_PRESETS: Dict[str, TrainerPreset] = {
            "baseline_xgboost": TrainerPreset(
                trainer_key="xgboost",
                pipeline_key="identity",
                trainer_params={
                    "artifact_id": "surrogate_v1",
                    "n_estimators": 420,
                    "max_depth": 6,
                    "learning_rate": 0.05,
                },
            ),
            "baseline_stagewise": TrainerPreset(
                trainer_key="symbolic_stagewise",
                pipeline_key="identity",
                trainer_params={
                    "artifact_id": "surrogate_stagewise",
                    "strategy": {
                        "force_linear_base": "auto",
                        "keep_search_trace": True,
                    },
                    "search_core": {
                        "max_added_terms": 12,
                        "topk_features": 8,
                        "max_expr_depth": 6,
                    },
                    "search_family": {
                        "unary_ops": ["square", "sin", "cos", "tanh"],
                        "auto_nested_allowed_ops": ["square", "sin", "cos", "tanh"],
                    },
                    "search_online_beam": {
                        "enabled": True,
                        "width": 6,
                        "bundle_size": 3,
                    },
                },
            ),
        }

        # `symbolic_stagewise` trainer_params supports both:
        # 1) flat keys like `search_max_added_terms`
        # 2) grouped keys like `search_core.max_added_terms`
        # If both appear in the same trainer_params object, flat keys win.
        TRAINER_PRESET_RESOURCE_PROFILES = {
            key: dict(TRAINER_RESOURCE_PROFILES.get(str(preset.trainer_key), {}))
            for key, preset in TRAINER_PRESETS.items()
        }


        _TRAIN_COMPONENT_KEYS = (
            "trainer_key",
            "pipeline_key",
            "trainer_params",
            "pipeline_params",
            "biases",
            "numericizer_key",
            "numericizer_params",
            "model_spec",
            "training_init",
            "state_backend",
            "execution",
            "capabilities",
        )

        _TRAIN_RUNTIME_KEYS = (
            "capability_strict",
            "eval_splits",
            "output_dir",
            "run_name",
            "portfolio_parallel_mode",
            "portfolio_max_workers",
            "portfolio_fail_fast",
            "portfolio_gpu_strategy",
            "portfolio_gpu_devices",
        )


        def resolve_train_section(train_raw: Mapping[str, Any]) -> Dict[str, Any]:
            raw = dict(train_raw or {})
            preset_key = str(raw.pop("preset_key", "baseline_xgboost"))

            preset = TRAINER_PRESETS.get(preset_key)
            if preset is None:
                known = ", ".join(sorted(TRAINER_PRESETS.keys()))
                raise KeyError(f"Unknown train preset: '{preset_key}'. Available: [{known}]")

            resolved: Dict[str, Any] = {
                "trainer_key": str(preset.trainer_key),
                "pipeline_key": str(preset.pipeline_key),
                "trainer_params": dict(preset.trainer_params),
                "pipeline_params": dict(preset.pipeline_params),
                "biases": list(preset.biases),
                "numericizer_key": str(preset.numericizer_key),
                "numericizer_params": dict(preset.numericizer_params),
                "model_spec": None if preset.model_spec is None else dict(preset.model_spec),
                "training_init": None if preset.training_init is None else dict(preset.training_init),
                "state_backend": None if preset.state_backend is None else dict(preset.state_backend),
                "capabilities": list(preset.capabilities),
                "capability_strict": bool(preset.capability_strict),
                "eval_splits": ["train", "test"],
                "output_dir": "runs/scaffold_run",
                "run_name": "scaffold_run",
                "execution": (
                    dict(EXECUTION_DEFAULTS)
                    if preset.execution is None
                    else dict(preset.execution)
                ),
                "portfolio_parallel_mode": str(EXECUTION_DEFAULTS.get("backend", "serial")),
                "portfolio_max_workers": EXECUTION_DEFAULTS.get("max_workers"),
                "portfolio_fail_fast": bool(EXECUTION_DEFAULTS.get("fail_fast", True)),
                "portfolio_gpu_strategy": str(EXECUTION_DEFAULTS.get("gpu_strategy", "none")),
                "portfolio_gpu_devices": list(EXECUTION_DEFAULTS.get("gpu_devices", [])),
            }

            for key in _TRAIN_COMPONENT_KEYS:
                if key not in raw:
                    continue
                if key in {"trainer_params", "pipeline_params", "numericizer_params"}:
                    merged = dict(resolved.get(key, {}))
                    merged.update(dict(raw[key]))
                    resolved[key] = merged
                elif key == "biases":
                    resolved[key] = list(raw[key])
                elif key == "model_spec":
                    resolved[key] = None if raw[key] is None else dict(raw[key])
                elif key == "training_init":
                    resolved[key] = None if raw[key] is None else dict(raw[key])
                elif key == "state_backend":
                    resolved[key] = None if raw[key] is None else dict(raw[key])
                elif key == "execution":
                    resolved[key] = None if raw[key] is None else dict(raw[key])
                elif key == "capabilities":
                    resolved[key] = list(raw[key])
                else:
                    resolved[key] = raw[key]

            for key in _TRAIN_RUNTIME_KEYS:
                if key in raw:
                    resolved[key] = raw[key]

            return resolved


        def resolve_payload(payload: Mapping[str, Any]) -> Dict[str, Any]:
            out: Dict[str, Any] = dict(payload or {})
            out["data"] = dict(out.get("data", {}))
            out["train"] = resolve_train_section(out.get("train", {}))
            return out
        """
    )


def _assembly_template() -> str:
    return dedent(
        """\
        from __future__ import annotations

        import importlib.util
        import json
        import sys
        from pathlib import Path
        from typing import Any, Dict


        def _load_project_config_module():
            cfg_path = Path(__file__).resolve().with_name("config.py")
            spec = importlib.util.spec_from_file_location("mlblack_project_config", cfg_path)
            if spec is None or spec.loader is None:
                raise ImportError(f"Cannot load project config module: {cfg_path}")
            mod = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = mod
            spec.loader.exec_module(mod)
            return mod


        def _ensure_mlblack_root() -> None:
            import os
            import sys

            def _is_mlblack_root(path: Path) -> bool:
                return bool(
                    (path / "project" / "scaffold.py").exists()
                    and (
                        (path / "core" / "orchestration" / "workflow.py").exists()
                        or (path / "core" / "workflow.py").exists()
                    )
                )

            env_root = os.environ.get("MLBLACK_ROOT")
            if env_root:
                p = Path(env_root).resolve()
                if _is_mlblack_root(p):
                    if str(p) not in sys.path:
                        sys.path.insert(0, str(p))
                    return

            here = Path(__file__).resolve().parent
            for parent in [here, *here.parents]:
                if _is_mlblack_root(parent):
                    if str(parent) not in sys.path:
                        sys.path.insert(0, str(parent))
                    return

            raise RuntimeError("Cannot locate mlblack root. Set MLBLACK_ROOT=<path-to-mlblack-repo> first.")


        def _load_payload(path: str | Path) -> Dict[str, Any]:
            p = Path(path)
            return json.loads(p.read_text(encoding="utf-8-sig"))


        def build_spec_from_config(path: str | Path):
            _ensure_mlblack_root()
            from project import build_scaffold_spec

            payload = _load_payload(path)
            cfg = _load_project_config_module()
            resolved = dict(cfg.resolve_payload(payload))
            return build_scaffold_spec(resolved)


        def run_from_config(path: str | Path):
            _ensure_mlblack_root()
            from project import run_project_scaffold

            spec = build_spec_from_config(path)
            return run_project_scaffold(spec)
        """
    )

def _run_train_template() -> str:
    return dedent(
        """\
        from __future__ import annotations

        import argparse
        from pathlib import Path

        from assembly import run_from_config


        def main() -> None:
            parser = argparse.ArgumentParser(description="Run mlblack project scaffold")
            parser.add_argument(
                "--config",
                type=str,
                default="configs/train_config.json",
                help="Path to scaffold config json",
            )
            args = parser.parse_args()

            config_path = Path(args.config)
            if not config_path.exists():
                raise FileNotFoundError(f"config not found: {config_path}")

            result = run_from_config(config_path)

            print("SCAFFOLD RUN RESULT")
            print(f"trainer={result.report['trainer_name']}")
            print(f"artifact_id={result.report['artifact']['artifact_id']}")
            for split, m in result.metrics.items():
                print(f"{split:5s} rmse={m['rmse']:.4f}  mae={m['mae']:.4f}  r2={m['r2']:.4f}")
            print(f"output_dir={result.output_dir}")


        if __name__ == "__main__":
            main()
        """
    )


def _prepare_data_template() -> str:
    return dedent(
        """\
        from __future__ import annotations

        # Put your data-cleaning script here.
        # Output target: data/processed.csv


        def main() -> None:
            raise NotImplementedError("Implement your cleaning logic and export data/processed.csv")


        if __name__ == "__main__":
            main()
        """
    )


def init_project(target_dir: Path | str, *, force: bool = False) -> Path:
    """Initialize an mlblack standard scaffold project."""
    root = Path(target_dir).resolve()
    root.mkdir(parents=True, exist_ok=True)

    if any(root.iterdir()) and not force:
        raise FileExistsError(f"Target directory not empty: {root}")

    for name in _PROJECT_FOLDERS:
        folder = root / name
        folder.mkdir(parents=True, exist_ok=True)
        if name not in _NON_PACKAGE_FOLDERS:
            _write_file(folder / "__init__.py", "", overwrite=force)
        _write_file(folder / "README.md", _folder_readme(name), overwrite=force)

    _write_file(root / "README.md", _root_readme(root.name), overwrite=force)
    _write_file(root / "START_HERE.md", _start_here(), overwrite=force)
    _write_file(root / ".mlblack-project", "marker = mlblack-scaffold-project\n", overwrite=force)
    _write_file(root / "catalog" / "entries.toml", _project_catalog_entries_template(), overwrite=force)

    _write_file(root / "configs" / "train_config.json", _sample_train_config(), overwrite=force)
    _write_file(
        root / "configs" / "train_config_stagewise_grouped.json",
        _sample_train_config_stagewise_grouped(),
        overwrite=force,
    )
    _write_file(root / "schema" / "execution_schema.py", _execution_schema_template(), overwrite=force)
    _write_file(root / "schema" / "trainer_contracts.py", _trainer_contracts_schema_template(), overwrite=force)
    _write_file(root / "config.py", _config_template(), overwrite=force)
    _write_file(root / "assembly.py", _assembly_template(), overwrite=force)
    _write_file(root / "run_train.py", _run_train_template(), overwrite=force)
    _write_file(root / "scripts" / "prepare_data.py", _prepare_data_template(), overwrite=force)

    return root

def _to_bias_specs(items: Sequence[Mapping[str, Any]]) -> tuple[BiasSpec, ...]:
    out: list[BiasSpec] = []
    for item in items:
        key = str(item.get("key", "noop"))
        params = dict(item.get("params", {}))
        out.append(BiasSpec(key=key, params=params))
    return tuple(out)


def _to_capability_specs(items: Sequence[Mapping[str, Any]]) -> tuple[CapabilitySpec, ...]:
    out: list[CapabilitySpec] = []
    for item in items:
        key = str(item.get("key", "noop"))
        params = dict(item.get("params", {}))
        out.append(CapabilitySpec(key=key, params=params))
    return tuple(out)


def _to_model_spec(item: Mapping[str, Any] | None) -> ModelSpec | None:
    if item is None:
        return None
    raw = dict(item)
    return ModelSpec(
        model_id=str(raw.get("model_id", "default_model")),
        feature_names=None if raw.get("feature_names") is None else tuple(str(x) for x in raw.get("feature_names", [])),
        target_names=None if raw.get("target_names") is None else tuple(str(x) for x in raw.get("target_names", [])),
        feature_indices=(
            None if raw.get("feature_indices") is None else tuple(int(x) for x in raw.get("feature_indices", []))
        ),
        target_indices=(
            None if raw.get("target_indices") is None else tuple(int(x) for x in raw.get("target_indices", []))
        ),
        strict=bool(raw.get("strict", True)),
        metadata=None if raw.get("metadata") is None else dict(raw.get("metadata", {})),
    )


def _to_model_specs(items: Sequence[Mapping[str, Any]]) -> tuple[ModelSpec, ...]:
    out: list[ModelSpec] = []
    for item in items:
        model_spec = _to_model_spec(item)
        if model_spec is not None:
            out.append(model_spec)
    return tuple(out)


def _build_sqlalchemy_url(
    src: Mapping[str, Any],
    *,
    source_name: str,
    default_driver: str,
    default_port: int,
) -> tuple[str, str]:
    raw_url = _expand_env_refs(str(src.get("url", ""))).strip()
    if raw_url:
        custom_label = str(src.get("label", "")).strip()
        if custom_label:
            return raw_url, custom_label
        safe_url = re.sub(r"://([^:/@]+):[^@]*@", r"://\1:***@", raw_url)
        return raw_url, safe_url

    host = _expand_env_refs(str(src.get("host", "127.0.0.1"))).strip() or "127.0.0.1"
    database = _expand_env_refs(str(src.get("database", src.get("db", "")))).strip()
    user = _expand_env_refs(str(src.get("user", src.get("username", "")))).strip()
    password = _expand_env_refs(str(src.get("password", ""))).strip()
    driver = _expand_env_refs(str(src.get("driver", default_driver))).strip() or default_driver

    try:
        port = int(src.get("port", default_port))
    except Exception as exc:
        raise ValueError(f"{source_name}: invalid port value") from exc

    if not database:
        raise ValueError(f"{source_name}: SQL source requires 'database' (or full 'url')")

    auth = ""
    if user:
        auth = quote_plus(user)
        if password:
            auth += f":{quote_plus(password)}"
        auth += "@"

    url = f"{driver}://{auth}{host}:{port}/{database}"
    safe_label = f"{driver}://{host}:{port}/{database}"
    return url, safe_label


def _read_sqlalchemy_query_source(
    *,
    name: str,
    url: str,
    sql: str | None = None,
    table: str | None = None,
    source_kind: str = "sql",
    connect_args: Mapping[str, Any] | None = None,
) -> pd.DataFrame:
    stmt = str(sql or "").strip()
    table_name = str(table or "").strip()
    if not stmt and table_name:
        stmt = f"SELECT * FROM {table_name}"
    if not stmt:
        raise ValueError(f"{name}: {source_kind} source requires 'sql' or 'table'")

    try:
        from sqlalchemy import create_engine
    except Exception as exc:
        raise ImportError(
            f"{source_kind} source requires sqlalchemy and matching DB driver (e.g. psycopg2/pymysql)"
        ) from exc

    kwargs: Dict[str, Any] = {}
    if connect_args is not None:
        kwargs["connect_args"] = dict(connect_args)

    engine = create_engine(url, **kwargs)
    try:
        with engine.connect() as conn:
            frame = pd.read_sql_query(stmt, conn)
    finally:
        engine.dispose()
    return frame


def _load_one_source_frame(source_raw: Mapping[str, Any], *, index: int) -> tuple[pd.DataFrame, Dict[str, Any]]:
    src = dict(source_raw)
    name = str(src.get("name", f"source_{index}"))
    kind = _normalize_source_kind(src.get("kind", "csv"))

    frame: pd.DataFrame
    source_label = ""
    if kind == "csv":
        path = _expand_env_refs(str(src.get("path", "")))
        if not path:
            raise ValueError(f"{name}: csv source requires 'path'")
        source_label = path
        frame = pd.read_csv(path)
    elif kind == "sqlite_sql":
        db_path = _expand_env_refs(str(src.get("db_path", "")))
        sql = str(src.get("sql", "")).strip()
        if not db_path or not sql:
            raise ValueError(f"{name}: sqlite_sql source requires 'db_path' and 'sql'")
        source_label = db_path
        with sqlite3.connect(db_path) as conn:
            frame = pd.read_sql_query(sql, conn)
    elif kind == "sqlite_table":
        db_path = _expand_env_refs(str(src.get("db_path", "")))
        table = str(src.get("table", "")).strip()
        if not db_path or not table:
            raise ValueError(f"{name}: sqlite_table source requires 'db_path' and 'table'")
        source_label = db_path
        sql = f'SELECT * FROM "{table}"'
        with sqlite3.connect(db_path) as conn:
            frame = pd.read_sql_query(sql, conn)
    elif kind == "sql":
        url = _expand_env_refs(str(src.get("url", ""))).strip()
        if not url:
            raise ValueError(f"{name}: sql source requires 'url'")
        source_label = str(src.get("label", url))
        frame = _read_sqlalchemy_query_source(
            name=name,
            url=url,
            sql=src.get("sql", None),
            table=src.get("table", None),
            source_kind="sql",
            connect_args=src.get("connect_args", None),
        )
    elif kind in {"postgres_sql", "postgres_table", "postgresql_sql", "postgresql_table"}:
        url, source_label = _build_sqlalchemy_url(
            src,
            source_name=name,
            default_driver="postgresql+psycopg2",
            default_port=5432,
        )
        frame = _read_sqlalchemy_query_source(
            name=name,
            url=url,
            sql=src.get("sql", None),
            table=src.get("table", None),
            source_kind=kind,
            connect_args=src.get("connect_args", None),
        )
    elif kind in {"mysql_sql", "mysql_table"}:
        url, source_label = _build_sqlalchemy_url(
            src,
            source_name=name,
            default_driver="mysql+pymysql",
            default_port=3306,
        )
        frame = _read_sqlalchemy_query_source(
            name=name,
            url=url,
            sql=src.get("sql", None),
            table=src.get("table", None),
            source_kind=kind,
            connect_args=src.get("connect_args", None),
        )
    else:
        raise ValueError(f"{name}: unsupported source kind '{kind}'")

    if frame.empty:
        raise ValueError(f"{name}: source returned empty frame")

    select_cols = tuple(str(c) for c in src.get("select_cols", src.get("select", [])))
    if select_cols:
        missing = [c for c in select_cols if c not in frame.columns]
        if missing:
            raise ValueError(f"{name}: select columns missing: {missing}")
        frame = frame[list(select_cols)].copy()

    rename_map = dict(src.get("rename", {}))
    if rename_map:
        frame = frame.rename(columns={str(k): str(v) for k, v in rename_map.items()})

    info = {
        "name": name,
        "kind": kind,
        "rows": int(frame.shape[0]),
        "cols": int(frame.shape[1]),
        "label": source_label,
        "on": _as_name_tuple(src.get("on", None)),
        "how": str(src.get("how", "")).strip().lower() or None,
        "prefix": str(src.get("prefix", "")).strip() or None,
    }
    return frame, info


def _prefix_non_key_columns(df: pd.DataFrame, *, on_keys: Sequence[str], prefix: str) -> pd.DataFrame:
    p = str(prefix).strip()
    if not p:
        return df
    on_set = set(str(x) for x in on_keys)
    rename_map = {str(c): f"{p}{c}" for c in df.columns if str(c) not in on_set}
    if not rename_map:
        return df
    return df.rename(columns=rename_map)


def _load_table_frame(spec: TableDataSpec) -> tuple[pd.DataFrame, Dict[str, Any]]:
    if spec.sources:
        source_rows: list[Dict[str, Any]] = []
        source_frames: list[pd.DataFrame] = []
        for i, item in enumerate(tuple(spec.sources)):
            frame, info = _load_one_source_frame(dict(item), index=i)
            source_frames.append(frame)
            source_rows.append(info)

        if not source_frames:
            raise ValueError("sources is empty")

        names = [str(x["name"]) for x in source_rows]
        base_idx = 0
        if spec.base_source:
            wanted = str(spec.base_source)
            if wanted not in names:
                raise ValueError(f"base_source '{wanted}' not found in sources: {names}")
            base_idx = int(names.index(wanted))

        merged = source_frames[base_idx].copy()
        base_info = dict(source_rows[base_idx])
        global_on = tuple(_as_name_tuple(spec.merge_on))
        global_how = str(spec.merge_how or "inner").strip().lower()
        if not global_how:
            global_how = "inner"

        base_prefix = str(base_info.get("prefix") or "").strip()
        if base_prefix:
            base_on = tuple(_as_name_tuple(base_info.get("on"))) or global_on
            merged = _prefix_non_key_columns(merged, on_keys=base_on, prefix=base_prefix)
            base_info["applied_prefix"] = base_prefix

        lineage: list[Dict[str, Any]] = [dict(base_info)]
        for i, (frame, info) in enumerate(zip(source_frames, source_rows)):
            if i == base_idx:
                continue
            src_on = tuple(_as_name_tuple(info.get("on"))) or global_on
            if not src_on:
                raise ValueError(
                    f"source '{info['name']}' missing merge keys. Set data.merge_on or source.on"
                )
            missing_left = [c for c in src_on if c not in merged.columns]
            missing_right = [c for c in src_on if c not in frame.columns]
            if missing_left:
                raise ValueError(f"merge key(s) missing in left frame for source '{info['name']}': {missing_left}")
            if missing_right:
                raise ValueError(f"merge key(s) missing in source '{info['name']}': {missing_right}")

            src_how = str(info.get("how") or global_how).strip().lower()
            src_prefix = str(info.get("prefix") or "").strip()
            right = _prefix_non_key_columns(frame.copy(), on_keys=src_on, prefix=src_prefix)
            merged = merged.merge(right, on=list(src_on), how=src_how, suffixes=("", f"__{info['name']}"))

            row = dict(info)
            row["merge_on"] = tuple(src_on)
            row["merge_how"] = str(src_how)
            lineage.append(row)

        meta = {
            "source_mode": "composed",
            "base_source": str(base_info["name"]),
            "merge_on": tuple(global_on),
            "merge_how": str(global_how),
            "sources": tuple(lineage),
            "source_label": "composed_sources",
        }
        return merged, meta

    csv_path = _expand_env_refs(str(spec.csv_path))
    if not csv_path:
        raise ValueError("data.csv_path is required when data.sources is empty")
    frame = pd.read_csv(csv_path)
    if frame.empty:
        raise ValueError(f"CSV is empty: {csv_path}")
    meta = {
        "source_mode": "csv",
        "csv_path": csv_path,
        "source_label": csv_path,
        "sources": tuple(),
        "merge_on": tuple(),
        "merge_how": None,
        "base_source": None,
    }
    return frame, meta


def _build_feature_frame(df: pd.DataFrame, spec: TableDataSpec) -> tuple[pd.DataFrame, list[str]]:
    recipe = str(getattr(spec, "feature_recipe", "raw_all_numeric") or "raw_all_numeric").strip().lower()

    if recipe in {"raw_all_numeric", "default", "all_numeric"}:
        fold_cols = [c for c in df.columns if str(c).startswith("test_fold_")]

        drop_cols = set(str(c) for c in spec.drop_cols)
        drop_cols.add(spec.target_col)
        if spec.date_col and spec.date_col in df.columns:
            drop_cols.add(spec.date_col)

        # Avoid leakage from fold markers.
        for c in fold_cols:
            drop_cols.add(c)

        feature_cols = [c for c in df.columns if c not in drop_cols]
        if not feature_cols:
            raise ValueError("No feature columns remain after drop rules")
        return df[feature_cols].copy(), feature_cols

    if recipe == "work_ci_interval_v1":
        date_col = str(spec.date_col or "date")
        if date_col not in df.columns:
            raise ValueError(f"feature_recipe=work_ci_interval_v1 requires date column '{date_col}'")

        required = [
            "is_holiday_near",
            "is_holiday_mid",
            "is_nonwork_weekend",
            "is_bad_weather",
            "aqi",
            "wind",
            "life_impact",
        ]
        missing = [c for c in required if c not in df.columns]
        if missing:
            raise ValueError(f"feature_recipe=work_ci_interval_v1 missing columns: {missing}")

        d = pd.to_datetime(df[date_col], errors="coerce")
        if bool(d.isna().any()):
            raise ValueError(f"feature_recipe=work_ci_interval_v1 failed to parse dates in '{date_col}'")

        dow = d.dt.dayofweek.to_numpy()
        month = d.dt.month.to_numpy()
        ci_series = pd.to_numeric(df[spec.target_col], errors="coerce")

        X_df = pd.DataFrame(
            {
                "intercept": 1.0,
                "dow_sin": np.sin(2.0 * np.pi * dow / 7.0),
                "dow_cos": np.cos(2.0 * np.pi * dow / 7.0),
                "month_sin": np.sin(2.0 * np.pi * month / 12.0),
                "month_cos": np.cos(2.0 * np.pi * month / 12.0),
                "is_holiday_near": df["is_holiday_near"].astype(float),
                "is_holiday_mid": df["is_holiday_mid"].astype(float),
                "is_nonwork_weekend": df["is_nonwork_weekend"].astype(float),
                "is_bad_weather": df["is_bad_weather"].astype(float),
                "aqi_scaled": pd.to_numeric(df["aqi"], errors="coerce").fillna(0.0) / 100.0,
                "wind_scaled": pd.to_numeric(df["wind"], errors="coerce").fillna(0.0) / 10.0,
                "life_impact": pd.to_numeric(df["life_impact"], errors="coerce").fillna(0.0),
                "ci_lag1": ci_series.shift(1).bfill(),
            }
        )
        return X_df, list(X_df.columns)

    raise ValueError(
        f"Unsupported feature_recipe '{spec.feature_recipe}'. "
        "Use one of: raw_all_numeric, work_ci_interval_v1."
    )


def _table_to_bundle(spec: TableDataSpec) -> TrainDataBundle:
    df, source_meta = _load_table_frame(spec)
    if df.empty:
        raise ValueError("input table is empty after loading sources")

    if spec.target_col not in df.columns:
        raise ValueError(f"target_col '{spec.target_col}' not found")

    split_mode = str(spec.split_mode).strip().lower()
    if split_mode not in {"fold_flag", "ratio"}:
        raise ValueError("split_mode must be 'fold_flag' or 'ratio'")

    X_df, feature_cols = _build_feature_frame(df, spec)
    y_df = df[[spec.target_col]].copy()

    for c in feature_cols:
        X_df[c] = pd.to_numeric(X_df[c], errors="coerce")
    y_df[spec.target_col] = pd.to_numeric(y_df[spec.target_col], errors="coerce")

    if X_df.isna().any().any() or y_df.isna().any().any():
        bad = [c for c in feature_cols if X_df[c].isna().any()]
        if y_df[spec.target_col].isna().any():
            bad.append(spec.target_col)
        raise ValueError(
            "Found NaN after numeric conversion; please clean upstream data first. "
            f"Columns: {bad}"
        )

    X = X_df.to_numpy(dtype=float)
    y = y_df.to_numpy(dtype=float)
    n = int(len(df))

    if split_mode == "fold_flag":
        if spec.test_fold_col not in df.columns:
            raise ValueError(f"test_fold_col '{spec.test_fold_col}' not found")
        test_mask = pd.to_numeric(df[spec.test_fold_col], errors="coerce").fillna(0).astype(int).to_numpy() == 1
    else:
        ratio = float(spec.test_ratio)
        if not (0.0 < ratio < 1.0):
            raise ValueError("test_ratio must be in (0, 1)")
        rng = np.random.default_rng(int(spec.random_seed))
        idx = np.arange(n)
        rng.shuffle(idx)
        n_test = max(1, int(round(n * ratio)))
        test_idx = idx[:n_test]
        test_mask = np.zeros(n, dtype=bool)
        test_mask[test_idx] = True

    if int(np.sum(test_mask)) <= 0:
        raise ValueError("No test rows selected by split rule")

    train_mask = ~test_mask

    train_ds = ProcessedDataset(
        X_train=np.asarray(X[train_mask], dtype=float),
        y_train=np.asarray(y[train_mask], dtype=float),
        feature_names=tuple(feature_cols),
        target_names=(spec.target_col,),
        metadata={
            "source": str(source_meta.get("source_label", "unknown")),
            "source_mode": str(source_meta.get("source_mode", "unknown")),
            "split": "train",
            "split_mode": split_mode,
        },
    )

    test_ds = ProcessedDataset(
        X_train=np.asarray(X[test_mask], dtype=float),
        y_train=np.asarray(y[test_mask], dtype=float),
        feature_names=tuple(feature_cols),
        target_names=(spec.target_col,),
        metadata={
            "source": str(source_meta.get("source_label", "unknown")),
            "source_mode": str(source_meta.get("source_mode", "unknown")),
            "split": "test",
            "split_mode": split_mode,
        },
    )

    return TrainDataBundle(
        train=train_ds,
        test=test_ds,
        metadata={
            "reader": "table_compose" if spec.sources else "table_csv",
            "source_mode": str(source_meta.get("source_mode", "unknown")),
            "csv_path": None if not source_meta.get("csv_path") else str(source_meta.get("csv_path")),
            "data_sources": tuple(source_meta.get("sources", tuple())),
            "base_source": source_meta.get("base_source"),
            "merge_on": tuple(source_meta.get("merge_on", tuple())),
            "merge_how": source_meta.get("merge_how"),
            "target_col": spec.target_col,
            "feature_cols": tuple(feature_cols),
            "feature_recipe": str(spec.feature_recipe),
            "n_total": int(n),
            "n_train": int(np.sum(train_mask)),
            "n_test": int(np.sum(test_mask)),
            "split_mode": split_mode,
            "test_fold_col": spec.test_fold_col,
            "test_ratio": float(spec.test_ratio),
        },
    )


def build_scaffold_spec(payload: Mapping[str, Any]) -> ScaffoldSpec:
    data_raw = dict(payload.get("data", {}))
    train_raw = dict(payload.get("train", {}))

    if not data_raw:
        raise ValueError("scaffold config missing 'data' section")

    target_col = str(data_raw.get("target_col", "")).strip()
    if not target_col:
        raise ValueError("data.target_col is required")

    csv_path = _expand_env_refs(str(data_raw.get("csv_path", ""))).strip()
    sources = tuple(data_raw.get("sources", []))
    if not csv_path and not sources:
        raise ValueError("data requires either csv_path or non-empty sources")

    merge_on = _as_name_tuple(data_raw.get("merge_on", []))
    if len(sources) > 1 and not merge_on and not any(_as_name_tuple(dict(s).get("on")) for s in sources):
        raise ValueError("multi-source data requires data.merge_on or per-source 'on' keys")

    data_spec = TableDataSpec(
        csv_path=csv_path,
        sources=tuple(dict(x) for x in sources),
        merge_on=tuple(merge_on),
        merge_how=str(data_raw.get("merge_how", "inner")),
        base_source=(None if data_raw.get("base_source") is None else str(data_raw.get("base_source"))),
        target_col=target_col,
        date_col=data_raw.get("date_col", "date"),
        drop_cols=tuple(data_raw.get("drop_cols", [])),
        feature_recipe=str(data_raw.get("feature_recipe", "raw_all_numeric")),
        split_mode=str(data_raw.get("split_mode", "fold_flag")),
        test_fold_col=str(data_raw.get("test_fold_col", "test_fold_10")),
        test_ratio=float(data_raw.get("test_ratio", 0.2)),
        random_seed=int(data_raw.get("random_seed", 42)),
    )

    train_spec = TrainStageSpec(
        trainer_key=str(train_raw.get("trainer_key", "xgboost")),
        pipeline_key=str(train_raw.get("pipeline_key", "identity")),
        trainer_params=dict(train_raw.get("trainer_params", {})),
        pipeline_params=dict(train_raw.get("pipeline_params", {})),
        biases=tuple(train_raw.get("biases", [])),
        numericizer_key=str(train_raw.get("numericizer_key", "default")),
        numericizer_params=dict(train_raw.get("numericizer_params", {})),
        model_spec=None if train_raw.get("model_spec") is None else dict(train_raw.get("model_spec", {})),
        model_specs=tuple(dict(x) for x in train_raw.get("model_specs", [])),
        training_init=None if train_raw.get("training_init") is None else dict(train_raw.get("training_init", {})),
        state_backend=None if train_raw.get("state_backend") is None else dict(train_raw.get("state_backend", {})),
        execution=None if train_raw.get("execution") is None else dict(train_raw.get("execution", {})),
        capabilities=tuple(train_raw.get("capabilities", [])),
        capability_strict=bool(train_raw.get("capability_strict", False)),
        eval_splits=tuple(train_raw.get("eval_splits", ["train", "test"])),
        output_dir=_expand_env_refs(str(train_raw.get("output_dir", "runs/scaffold_run"))),
        run_name=str(train_raw.get("run_name", "scaffold_run")),
        portfolio_parallel_mode=str(train_raw.get("portfolio_parallel_mode", "serial")),
        portfolio_max_workers=(
            None if train_raw.get("portfolio_max_workers") is None else int(train_raw.get("portfolio_max_workers"))
        ),
        portfolio_fail_fast=bool(train_raw.get("portfolio_fail_fast", True)),
        portfolio_gpu_strategy=str(train_raw.get("portfolio_gpu_strategy", "none")),
        portfolio_gpu_devices=tuple(train_raw.get("portfolio_gpu_devices", [])),
    )

    if train_spec.model_spec is not None and train_spec.model_specs:
        raise ValueError("train.model_spec and train.model_specs are mutually exclusive")

    return ScaffoldSpec(data=data_spec, train=train_spec)


def load_scaffold_spec(path: str | Path) -> ScaffoldSpec:
    p = Path(path)
    payload = json.loads(p.read_text(encoding="utf-8-sig"))
    return build_scaffold_spec(payload)


def _resolve_state_store_cfg(
    train_spec: TrainStageSpec,
) -> tuple[Mapping[str, Any] | None, Mapping[str, Any] | None]:
    state_backend_cfg = None if train_spec.state_backend is None else dict(train_spec.state_backend)
    context_store_cfg: Mapping[str, Any] | None = None
    snapshot_store_cfg: Mapping[str, Any] | None = None
    if state_backend_cfg is not None:
        context_store_cfg = (
            None if state_backend_cfg.get("context") is None else dict(state_backend_cfg.get("context", {}))
        )
        snapshot_store_cfg = None if state_backend_cfg.get("snapshot") is None else dict(
            state_backend_cfg.get("snapshot", {})
        )
    return context_store_cfg, snapshot_store_cfg


def _build_semantic_flow_spec(
    spec: ScaffoldSpec,
    *,
    model_spec: ModelSpec | None = None,
    run_name: str | None = None,
    output_dir: str | None = None,
    context_store_cfg: Mapping[str, Any] | None = None,
    snapshot_store_cfg: Mapping[str, Any] | None = None,
) -> SemanticTrainFlowSpec:
    resolved_execution = coerce_execution_spec(
        spec.train.execution,
        fallback_backend=str(spec.train.portfolio_parallel_mode),
        fallback_max_workers=spec.train.portfolio_max_workers,
        fallback_fail_fast=bool(spec.train.portfolio_fail_fast),
        fallback_gpu_strategy=str(spec.train.portfolio_gpu_strategy),
        fallback_gpu_devices=tuple(spec.train.portfolio_gpu_devices),
    )
    trainer_assembly = TrainerAssemblySpec(
        trainer_key=spec.train.trainer_key,
        trainer_params=dict(spec.train.trainer_params),
        pipeline_key=spec.train.pipeline_key,
        pipeline_params=dict(spec.train.pipeline_params),
        biases=_to_bias_specs(spec.train.biases),
    )

    semantic_assembly = FlowAssemblySpec(
        trainer=trainer_assembly,
        numericizer=NumericizerSpec(
            key=str(spec.train.numericizer_key),
            params=dict(spec.train.numericizer_params),
        ),
        capabilities=_to_capability_specs(spec.train.capabilities),
    )

    flow_spec = SemanticTrainFlowSpec(
        assembly=semantic_assembly,
        execution=resolved_execution,
        training_init=None if spec.train.training_init is None else dict(spec.train.training_init),
        eval_splits=tuple(spec.train.eval_splits),
        output_dir=str(output_dir or spec.train.output_dir),
        save_artifact=True,
        save_report=True,
        model_spec=model_spec,
        capability_strict=bool(spec.train.capability_strict),
        run_name=str(run_name or spec.train.run_name),
        context_store=context_store_cfg,
        snapshot_store=snapshot_store_cfg,
        portfolio_parallel_mode=str(spec.train.portfolio_parallel_mode),
        portfolio_max_workers=spec.train.portfolio_max_workers,
        portfolio_fail_fast=bool(spec.train.portfolio_fail_fast),
        portfolio_gpu_strategy=str(spec.train.portfolio_gpu_strategy),
        portfolio_gpu_devices=tuple(spec.train.portfolio_gpu_devices),
    )
    return flow_spec


def run_project_scaffold_portfolio(spec: ScaffoldSpec) -> TrainPortfolioResult:
    model_specs = _to_model_specs(spec.train.model_specs)
    if not model_specs:
        raise ValueError("run_project_scaffold_portfolio requires non-empty train.model_specs")

    bundle = _table_to_bundle(spec.data)
    context_store_cfg, snapshot_store_cfg = _resolve_state_store_cfg(spec.train)
    base_flow_spec = _build_semantic_flow_spec(
        spec,
        context_store_cfg=context_store_cfg,
        snapshot_store_cfg=snapshot_store_cfg,
    )
    return run_semantic_portfolio_flow(
        bundle,
        spec=base_flow_spec,
        model_specs=model_specs,
    )


def run_project_scaffold(spec: ScaffoldSpec) -> TrainFlowResult:
    if spec.train.model_specs:
        portfolio = run_project_scaffold_portfolio(spec)
        best_model_id = portfolio.summary.get("best_model_id")
        selected_id = str(best_model_id) if best_model_id is not None else next(iter(portfolio.runs.keys()))
        if selected_id not in portfolio.runs:
            selected_id = next(iter(portfolio.runs.keys()))
        result = portfolio.runs[selected_id]
        result.report["portfolio"] = dict(portfolio.summary)
        return result

    bundle = _table_to_bundle(spec.data)
    context_store_cfg, snapshot_store_cfg = _resolve_state_store_cfg(spec.train)
    flow_spec = _build_semantic_flow_spec(
        spec,
        model_spec=_to_model_spec(spec.train.model_spec),
        context_store_cfg=context_store_cfg,
        snapshot_store_cfg=snapshot_store_cfg,
    )
    return run_semantic_train_flow(bundle, spec=flow_spec)












