from core.symbolic.feature_space.activation_config import (
    DynamicActivationConfig,
    parse_family_budget_csv,
    resolve_dynamic_activation_kwargs,
)
from core.symbolic.feature_space.candidate_pool import (
    CandidateTerm,
    _build_candidate_pool,
    _expand_candidate_pool_from_residual,
    _prune_candidate_pool,
    augment_candidate_pool_with_conditional_config,
    build_conditional_candidate_terms,
)
from core.symbolic.feature_space.builder import (
    CandidatePoolConfig,
    build_candidate_pool,
    build_full_candidate_pool,
)
from core.symbolic.feature_space.batch_interval_utils import (
    as_2d,
    batched_ridge_predict,
    design_matrix_for_genome,
    interval_metrics_batch,
    symmetric_interval_batch,
)
from core.symbolic.feature_space.cv_splitter import build_rolling_splits
from core.symbolic.feature_space.evaluation_cache_key import (
    DEFAULT_META_SIGNATURE_KEYS,
    build_meta_signature,
    build_subset_meta_cache_key,
    normalize_subset_key,
)
from core.symbolic.feature_space.branch_evaluator import (
    BranchEvaluationConfig,
    evaluate_regime_fold,
    evaluate_global_fold,
    evaluate_strict4_fold,
    evaluate_symmetric_residual_fold_batch,
)
from core.symbolic.feature_space.feature_bundle import (
    FeatureBundle,
    FeatureEngineeringConfig,
    build_feature_bundle,
)
from core.symbolic.feature_space.fold_report import build_interval_subset_report
from core.symbolic.feature_space.objective_policy import coverage_error, interval_objective_sort_key
from core.symbolic.feature_space.generation_grammar import (
    ActivationPlan,
    GrammarCandidate,
    generate_pair_candidates,
    generate_recursive_pair_candidates,
    generate_recursive_unary_candidates,
    generate_unary_candidates,
    lower_conditional_primitive_specs,
    make_seed_candidate,
    select_activation_plan,
)
from core.symbolic.feature_space.primitive_registry import (
    PairGrammarRule,
    PrimitiveRegistry,
    UnaryPrimitiveSpec,
    default_primitive_registry,
)
from core.symbolic.feature_space.subset_descriptor import (
    build_subset_candidate_metadata,
    build_subset_descriptor,
    build_subset_genome,
)
from core.symbolic.feature_space.regime_feature_pack import (
    RegimeFeaturePackConfig,
    RegimeFeaturePackResult,
    apply_regime_feature_pack,
)
from core.symbolic.feature_space.regime_router import (
    DefaultFixed4RegimeCanonicalizer,
    Fixed4RegimeKey,
    RegimeCanonicalizer,
    RegimePolicy,
    RegimeResolution,
    STRICT4_GATE_NAMES,
    STRICT4_HOLIDAY_KEYS,
    STRICT4_REGIME_ORDER,
    BranchTrainSelection,
    Strict4RouterSpec,
    Strict4Resolution,
    build_regime_index,
    holiday_union_indices,
    map_to_regime,
    map_to_strict4_regime,
    normalize_regime_key,
    normalize_fixed4_key,
    regime_keys_from_X,
    resolve_regime,
    resolve_branch_train_selection,
    resolve_strict4,
    strict4_keys_from_X,
)
from core.symbolic.feature_space.temporal_feature_pack import (
    TemporalFeaturePackConfig,
    TemporalFeaturePackResult,
    apply_temporal_feature_pack,
)
from core.symbolic.feature_space.lag_utils import make_lag_from_history, parse_float_list_csv, parse_int_list_csv

__all__ = [
    "DynamicActivationConfig",
    "as_2d",
    "batched_ridge_predict",
    "build_meta_signature",
    "build_rolling_splits",
    "build_subset_meta_cache_key",
    "parse_family_budget_csv",
    "resolve_dynamic_activation_kwargs",
    "CandidateTerm",
    "BranchEvaluationConfig",
    "evaluate_regime_fold",
    "CandidatePoolConfig",
    "FeatureBundle",
    "FeatureEngineeringConfig",
    "build_feature_bundle",
    "build_interval_subset_report",
    "build_candidate_pool",
    "build_full_candidate_pool",
    "design_matrix_for_genome",
    "DEFAULT_META_SIGNATURE_KEYS",
    "evaluate_global_fold",
    "evaluate_strict4_fold",
    "evaluate_symmetric_residual_fold_batch",
    "_build_candidate_pool",
    "_expand_candidate_pool_from_residual",
    "_prune_candidate_pool",
    "augment_candidate_pool_with_conditional_config",
    "ActivationPlan",
    "GrammarCandidate",
    "build_conditional_candidate_terms",
    "generate_pair_candidates",
    "generate_recursive_pair_candidates",
    "generate_recursive_unary_candidates",
    "generate_unary_candidates",
    "lower_conditional_primitive_specs",
    "make_seed_candidate",
    "select_activation_plan",
    "PairGrammarRule",
    "PrimitiveRegistry",
    "UnaryPrimitiveSpec",
    "default_primitive_registry",
    "coverage_error",
    "interval_metrics_batch",
    "interval_objective_sort_key",
    "build_subset_candidate_metadata",
    "build_subset_descriptor",
    "build_subset_genome",
    "make_lag_from_history",
    "parse_float_list_csv",
    "parse_int_list_csv",
    "TemporalFeaturePackConfig",
    "TemporalFeaturePackResult",
    "apply_temporal_feature_pack",
    "symmetric_interval_batch",
    "RegimeFeaturePackConfig",
    "RegimeFeaturePackResult",
    "apply_regime_feature_pack",
    "Fixed4RegimeKey",
    "RegimeCanonicalizer",
    "RegimePolicy",
    "RegimeResolution",
    "DefaultFixed4RegimeCanonicalizer",
    "STRICT4_GATE_NAMES",
    "STRICT4_HOLIDAY_KEYS",
    "STRICT4_REGIME_ORDER",
    "Strict4RouterSpec",
    "BranchTrainSelection",
    "Strict4Resolution",
    "build_regime_index",
    "holiday_union_indices",
    "map_to_regime",
    "map_to_strict4_regime",
    "normalize_regime_key",
    "normalize_fixed4_key",
    "normalize_subset_key",
    "regime_keys_from_X",
    "resolve_regime",
    "resolve_branch_train_selection",
    "resolve_strict4",
    "strict4_keys_from_X",
]
